### PR TITLE
bundling issue for browsers using es5

### PR DESCRIPTION
**Pull request by ivanvan93**
fixed es5 bundling issue, where package bundlers uses the es6 version of the file instead of the es5 friendly

### CODE REVIEW

**Comment by KaneCohen** [comment]
Which bundler are you using? As far as I understand "module" property should be used by ES6-aware tools.

**Comment by ivanvan93** [comment]
webpack 4.1.0

**Comment by ivanvan93** [comment]
i was looking at examples from other libraries, whether 'module' property was required in the package.json some of them don't

**Comment by KaneCohen** [comment]
It seems like you need a transpiler running with the webpack to convert ES6 code to ES5 code.

Removing `"module": "lib/tokenfield.js",` would mean that systems running clean ES6 would load already transpiled ES5 version - which is not ideal.

**Pull request closed without merging**
