### PR TITLE
Add evaluateValue method to sanitze or evaluate input value if needed.

### PR DESCRIPTION
**Pull request by simsim0709**
I just added helper method "evaluateValue". 
It is for users to evaluate input value before adding token. 
It is mostly same as "renderSetItemLabel" method but for input value. 

For example, 
```
myTokenfield.evaluateValue = function(value) {
  return value.replace(/[^a-z0-9]/gi, '');
}
```

### CODE REVIEW

**Comment by KaneCohen** [comment]
Seems reasonable, however I'm not sure "evaluateValue" would be a correct name for the method.

What's the point in adding that method to `_newItem` method? This method already should receive processed value from `_keyAction` method.

I'll think of a more appropriate name for the method and add it a bit later myself. Keeping issue open for now.

**Comment by simsim0709** [comment]
I added that method to `_newItem`, because it would cause problem adding empty token.

For example, if user override that method to below,

```
myToken.evaluateValue = function (value) {
  return value.replace(/[^a-z0-9]/gi, '');
}

```
In this case, if users type only special characters that should be replaced such as "!@#@#$%&", and press enter key, it will add token without value because all characters are replaced with empty value.
Therefore, I added that method to `_newItem`.

**Comment by KaneCohen** [comment]
Empty value shouldn't really be added because of the length check here:
https://github.com/KaneCohen/tokenfield/blob/master/lib/tokenfield.js#L585

**Comment by simsim0709** [comment]
Ok. I see. I didn't know that. :)

**Comment by KaneCohen** [comment]
Perfectly fine. I'll add code to handle this input event some time during the day (UTC).

**Comment by KaneCohen** [comment]
Pushed version 0.3.4 (had some troubled with 0.3.3 in npm).
I've changed name of the method to `onInput`, so in the code it would look like:

myToken.onInput = function(value) {
  return value.replace(/[^a-z0-9]/gi, '');
}

`onInput` also accepts second parameter - `event`, in case it is needed.

**Pull request closed without merging**
